In [13]:
import numpy as np
Day_number=np.arange(1,11)
Steps_walked=[4385,9552,7332,4504,5335,7552,8332,6504,5002,7079]
arr=np.array([Day_number,Steps_walked])
arr=arr.T
arr

array([[   1, 4385],
       [   2, 9552],
       [   3, 7332],
       [   4, 4504],
       [   5, 5335],
       [   6, 7552],
       [   7, 8332],
       [   8, 6504],
       [   9, 5002],
       [  10, 7079]])

In [14]:
new_arr=arr[:,1]+2000
arr[:,1]=new_arr
arr

array([[    1,  6385],
       [    2, 11552],
       [    3,  9332],
       [    4,  6504],
       [    5,  7335],
       [    6,  9552],
       [    7, 10332],
       [    8,  8504],
       [    9,  7002],
       [   10,  9079]])

In [15]:
matched=arr[:,1]>9000
matched
new_arr=arr[matched]
new_arr

array([[    2, 11552],
       [    3,  9332],
       [    6,  9552],
       [    7, 10332],
       [   10,  9079]])