In [4]:
import numpy as np
Day_number=np.arange(1,11)
Steps_walked=[6012,7079,6886,7230,4598,5564,6971,7763,8032,9569]
arr=np.array([Day_number,Steps_walked])
arr=arr.T
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [2]:
new_arr=arr[:,1]+2000
arr[:,1]=new_arr
arr

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [3]:
matched=arr[:,1]>9000
matched
new_arr=arr[matched]
new_arr

array([[    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])